In [4]:
from pathlib import Path
import os

if Path.cwd().name == "notebooks":
    os.chdir("..")

In [2]:
#biblioteke
import pandas as pd

from dotenv import load_dotenv
from google import genai

In [ ]:
#uvoz funkcije za generiranje sintetickih podataka
from src.generation import (generate_synthetic_dataset)

In [5]:
#putanje do podataka
PROCESSED_DIR = Path("data/processed")
TRAIN_PATH = PROCESSED_DIR / "train.csv"
SYNTHETIC_PATH = PROCESSED_DIR / "synthetic_train.csv"
AUGMENTED_PATH = PROCESSED_DIR / "augmented_train.csv"
TEST_PATH = PROCESSED_DIR / "test.csv"
CHALLENGE_PATH = PROCESSED_DIR / "challenge_test.csv"

In [14]:
#ucitavanje train podataka
train_df = pd.read_csv(TRAIN_PATH)

print("Broj train primjera:",len(train_df))
train_df.head()

Broj train primjera: 31268

,title,text,full_text,label,original_type,source_id
0,Philippine troops kill 14 Maoist rebels in cla...,MANILA ( ) - Philippine soldiers have killed 1...,Philippine troops kill 14 Maoist rebels in cla...,0,real,isot_13416
1,EU border controls could be extended in crisis...,BRUSSELS ( ) - Temporary border controls insid...,EU border controls could be extended in crisis...,0,real,isot_18702
2,Trump Whines About Hillary In Response To Obst...,After the news broke that Trump is going to be...,Trump Whines About Hillary In Response To Obst...,1,fake,isot_22321
3,Trump Throws PETTY Hissy Fit Because Bill Clin...,"Once again, Donald Trump is totally predictabl...",Trump Throws PETTY Hissy Fit Because Bill Clin...,1,fake,isot_24529
4,John Kerry commits more U.S. military aid for ...,TBILISI ( ) - Secretary of State John Kerry to...,John Kerry commits more U.S. military aid for ...,0,real,isot_08809

In [15]:
#izdvajanje stvarnih vijesti iz train skupa
real_train = (
    train_df[train_df["label"] == 0]
    .copy()
    .reset_index(drop=True)
)
print("Broj stvarnih vijesti:", len(real_train))
real_train.head()

Broj stvarnih vijesti: 16955

,title,text,full_text,label,original_type,source_id
0,Philippine troops kill 14 Maoist rebels in cla...,MANILA ( ) - Philippine soldiers have killed 1...,Philippine troops kill 14 Maoist rebels in cla...,0,real,isot_13416
1,EU border controls could be extended in crisis...,BRUSSELS ( ) - Temporary border controls insid...,EU border controls could be extended in crisis...,0,real,isot_18702
2,John Kerry commits more U.S. military aid for ...,TBILISI ( ) - Secretary of State John Kerry to...,John Kerry commits more U.S. military aid for ...,0,real,isot_08809
3,Germany lauds anti-nuclear campaign winning No...,BERLIN ( ) - Germany on Friday welcomed the No...,Germany lauds anti-nuclear campaign winning No...,0,real,isot_17983
4,"In Cuba visit, Colorado governor sees governme...",HAVANA ( ) - The governor of Colorado said on ...,"In Cuba visit, Colorado governor sees governme...",0,real,isot_05598

In [16]:
# ucitavanje Gemini API kljuca

load_dotenv(".env")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY nije pronaden")

client = genai.Client(
    api_key=GEMINI_API_KEY
)

GENERATION_MODEL = "gemini-3.5-flash-lite"

In [17]:
N_GENERATION_SOURCES = 1000

#odabir stvarnih train vrijednosti koje ce se koristiti za generiranje
generation_sources = (
    real_train
    .sample(
        n=min(N_GENERATION_SOURCES, len(real_train)),
        random_state=42
    )
    .reset_index(drop=True)
)

print("Broj originalnih izvora:", len(generation_sources))
print("Maksimalan broj synthetic primjera:", len(generation_sources) * 3)

Broj originalnih izvora: 1000
Maksimalan broj synthetic primjera: 3000

In [18]:
#generiranje synthetic train skupa
synthetic_train = generate_synthetic_dataset(
        source_df=generation_sources,
        client=client,
        model_name=GENERATION_MODEL
)
print("Ukupno synthetic primjera:", len(synthetic_train))

Generiranje 1/1000
Generiranje 2/1000
Generiranje 3/1000
Generiranje 4/1000
Generiranje 5/1000
Generiranje 6/1000
Generiranje 7/1000
Generiranje 8/1000
Generiranje 9/1000
Generiranje 10/1000
Generiranje 11/1000
Generiranje 12/1000
Generiranje 13/1000
Generiranje 14/1000
Generiranje 15/1000
Generiranje 16/1000
Generiranje 17/1000
Generiranje 18/1000
Generiranje 19/1000
Generiranje 20/1000
Generiranje 21/1000
Generiranje 22/1000
Generiranje 23/1000
Generiranje 24/1000
Generiranje 25/1000
Generiranje 26/1000
Generiranje 27/1000
Generiranje 28/1000
Generiranje 29/1000
Generiranje 30/1000
Generiranje 31/1000
Generiranje 32/1000
Generiranje 33/1000
Generiranje 34/1000
Generiranje 35/1000
Generiranje 36/1000
Generiranje 37/1000
Generiranje 38/1000
Generiranje 39/1000
Generiranje 40/1000
Generiranje 41/1000
Generiranje 42/1000
Generiranje 43/1000
Generiranje 44/1000
Generiranje 45/1000
Generiranje 46/1000
Generiranje 47/1000
Generiranje 48/1000
Generiranje 49/1000
Generiranje 50/1000
Generiranje 51/1000
Generiranje 52/1000
Generiranje 53/1000
Generiranje 54/1000
Generiranje 55/1000
Generiranje 56/1000
Generiranje 57/1000
Generiranje 58/1000
Generiranje 59/1000
Generiranje 60/1000
Generiranje 61/1000
Generiranje 62/1000
Generiranje 63/1000
Generiranje 64/1000
Generiranje 65/1000
Generiranje 66/1000
Generiranje 67/1000
Generiranje 68/1000
Generiranje 69/1000
Generiranje 70/1000
Generiranje 71/1000
Generiranje 72/1000
Generiranje 73/1000
Generiranje 74/1000
Generiranje 75/1000
Generiranje 76/1000
Generiranje 77/1000
Generiranje 78/1000
Generiranje 79/1000
Generiranje 80/1000
Generiranje 81/1000
Generiranje 82/1000
Generiranje 83/1000
Generiranje 84/1000
Generiranje 85/1000
Generiranje 86/1000
Generiranje 87/1000
Generiranje 88/1000
Generiranje 89/1000
Generiranje 90/1000
Generiranje 91/1000
Generiranje 92/1000
Generiranje 93/1000
Generiranje 94/1000
Generiranje 95/1000
Generiranje 96/1000
Generiranje 97/1000
Generiranje 98/1000
Generiranje 99/1000
Generiranje 100/1000
Generiranje 101/1000
Generiranje 102/1000
Generiranje 103/1000
Generiranje 104/1000
Generiranje 105/1000
Generiranje 106/1000
Generiranje 107/1000
Generiranje 108/1000
Generiranje 109/1000
Generiranje 110/1000
Generiranje 111/1000
Generiranje 112/1000
Generiranje 113/1000
Generiranje 114/1000
Generiranje 115/1000
Generiranje 116/1000
Generiranje 117/1000
Generiranje 118/1000
Generiranje 119/1000
Generiranje 120/1000
Generiranje 121/1000
Generiranje 122/1000
Generiranje 123/1000
Generiranje 124/1000
Generiranje 125/1000
Generiranje 126/1000
Generiranje 127/1000
Generiranje 128/1000
Generiranje 129/1000
Generiranje 130/1000
Generiranje 131/1000
Generiranje 132/1000
Generiranje 133/1000
Generiranje 134/1000
Generiranje 135/1000
Generiranje 136/1000
Generiranje 137/1000
Generiranje 138/1000
Generiranje 139/1000
Generiranje 140/1000
Generiranje 141/1000
Generiranje 142/1000
Generiranje 143/1000
Generiranje 144/1000
Generiranje 145/1000
Generiranje 146/1000
Generiranje 147/1000
Generiranje 148/1000
Generiranje 149/1000
Generiranje 150/1000
Generiranje 151/1000
Generiranje 152/1000
Generiranje 153/1000
Generiranje 154/1000
Generiranje 155/1000
Generiranje 156/1000
Generiranje 157/1000
Generiranje 158/1000
Generiranje 159/1000
Generiranje 160/1000
Generiranje 161/1000
Generiranje 162/1000
Generiranje 163/1000
Generiranje 164/1000
Generiranje 165/1000
Generiranje 166/1000
Generiranje 167/1000
Generiranje 168/1000
Generiranje 169/1000
Generiranje 170/1000
Generiranje 171/1000
Generiranje 172/1000
Generiranje 173/1000
Generiranje 174/1000
Generiranje 175/1000
Generiranje 176/1000
Generiranje 177/1000
Generiranje 178/1000
Generiranje 179/1000
Generiranje 180/1000
Generiranje 181/1000
Generiranje 182/1000
Generiranje 183/1000
Generiranje 184/1000
Generiranje 185/1000
Generiranje 186/1000
Generiranje 187/1000
Generiranje 188/1000
Generiranje 189/1000
Generiranje 190/1000
Generiranje 191/1000
Generiranje 192/1000
Generiranje 193/1000
Generiranje 194/1000
Generiranje 195/1000
Generiranje 196/1000
Generiranje 197/1000
Generiranje 198/1000
Generiranje 199/1000
Generiranje 200/1000
Generiranje 201/1000
Generiranje 202/1000
Generiranje 203/1000
Generiranje 204/1000
Generiranje 205/1000
Generiranje 206/1000
Generiranje 207/1000
Generiranje 208/1000
Generiranje 209/1000
Generiranje 210/1000
Generiranje 211/1000
Generiranje 212/1000
Generiranje 213/1000
Generiranje 214/1000
Generiranje 215/1000
Generiranje 216/1000
Generiranje 217/1000
Generiranje 218/1000
Generiranje 219/1000
Generiranje 220/1000
Generiranje 221/1000
Generiranje 222/1000
Generiranje 223/1000
Generiranje 224/1000
Generiranje 225/1000
Generiranje 226/1000
Generiranje 227/1000
Generiranje 228/1000
Generiranje 229/1000
Generiranje 230/1000
Generiranje 231/1000
Generiranje 232/1000
Generiranje 233/1000
Generiranje 234/1000
Generiranje 235/1000
Generiranje 236/1000
Generiranje 237/1000
Generiranje 238/1000
Generiranje 239/1000
Generiranje 240/1000
Generiranje 241/1000
Generiranje 242/1000
Generiranje 243/1000
Generiranje 244/1000
Generiranje 245/1000
Generiranje 246/1000
Generiranje 247/1000
Generiranje 248/1000
Generiranje 249/1000
Generiranje 250/1000
Generiranje 251/1000
Generiranje 252/1000
Generiranje 253/1000
Generiranje 254/1000
Generiranje 255/1000
Generiranje 256/1000
Generiranje 257/1000
Generiranje 258/1000
Generiranje 259/1000
Generiranje 260/1000
Generiranje 261/1000
Generiranje 262/1000
Generiranje 263/1000
Generiranje 264/1000
Generiranje 265/1000
Generiranje 266/1000
Pokusaj 1 nije uspio: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.
Generiranje 267/1000
Generiranje 268/1000
Generiranje 269/1000
Generiranje 270/1000
Generiranje 271/1000
Generiranje 272/1000
Generiranje 273/1000
Generiranje 274/1000
Generiranje 275/1000
Generiranje 276/1000
Generiranje 277/1000
Generiranje 278/1000
Generiranje 279/1000
Generiranje 280/1000
Generiranje 281/1000
Generiranje 282/1000
Generiranje 283/1000
Generiranje 284/1000
Generiranje 285/1000
Generiranje 286/1000
Generiranje 287/1000
Generiranje 288/1000
Generiranje 289/1000
Generiranje 290/1000
Generiranje 291/1000
Generiranje 292/1000
Generiranje 293/1000
Generiranje 294/1000
Generiranje 295/1000
Generiranje 296/1000
Generiranje 297/1000
Generiranje 298/1000
Generiranje 299/1000
Generiranje 300/1000
Generiranje 301/1000
Generiranje 302/1000
Generiranje 303/1000
Generiranje 304/1000
Generiranje 305/1000
Generiranje 306/1000
Generiranje 307/1000
Generiranje 308/1000
Generiranje 309/1000
Generiranje 310/1000
Generiranje 311/1000
Generiranje 312/1000
Generiranje 313/1000
Generiranje 314/1000
Generiranje 315/1000
Generiranje 316/1000
Generiranje 317/1000
Generiranje 318/1000
Generiranje 319/1000
Generiranje 320/1000
Generiranje 321/1000
Generiranje 322/1000
Generiranje 323/1000
Generiranje 324/1000
Generiranje 325/1000
Generiranje 326/1000
Generiranje 327/1000
Generiranje 328/1000
Generiranje 329/1000
Generiranje 330/1000
Generiranje 331/1000
Generiranje 332/1000
Generiranje 333/1000
Generiranje 334/1000
Generiranje 335/1000
Generiranje 336/1000
Generiranje 337/1000
Generiranje 338/1000
Generiranje 339/1000
Generiranje 340/1000
Generiranje 341/1000
Generiranje 342/1000
Generiranje 343/1000
Generiranje 344/1000
Generiranje 345/1000
Generiranje 346/1000
Generiranje 347/1000
Generiranje 348/1000
Generiranje 349/1000
Generiranje 350/1000
Generiranje 351/1000
Generiranje 352/1000
Generiranje 353/1000
Generiranje 354/1000
Generiranje 355/1000
Generiranje 356/1000
Generiranje 357/1000
Generiranje 358/1000
Generiranje 359/1000
Generiranje 360/1000
Generiranje 361/1000
Generiranje 362/1000
Generiranje 363/1000
Generiranje 364/1000
Generiranje 365/1000
Generiranje 366/1000
Generiranje 367/1000
Generiranje 368/1000
Generiranje 369/1000
Generiranje 370/1000
Generiranje 371/1000
Generiranje 372/1000
Generiranje 373/1000
Generiranje 374/1000
Generiranje 375/1000
Generiranje 376/1000
Generiranje 377/1000
Pokusaj 1 nije uspio: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}}
Generiranje 378/1000
Generiranje 379/1000
Generiranje 380/1000
Generiranje 381/1000
Generiranje 382/1000
Generiranje 383/1000
Generiranje 384/1000
Generiranje 385/1000
Generiranje 386/1000
Generiranje 387/1000
Generiranje 388/1000
Generiranje 389/1000
Generiranje 390/1000
Generiranje 391/1000
Generiranje 392/1000
Generiranje 393/1000
Generiranje 394/1000
Generiranje 395/1000
Generiranje 396/1000
Generiranje 397/1000
Generiranje 398/1000
Generiranje 399/1000
Generiranje 400/1000
Generiranje 401/1000
Generiranje 402/1000
Generiranje 403/1000
Generiranje 404/1000
Generiranje 405/1000
Generiranje 406/1000
Generiranje 407/1000
Generiranje 408/1000
Generiranje 409/1000
Generiranje 410/1000
Generiranje 411/1000
Generiranje 412/1000
Generiranje 413/1000
Generiranje 414/1000
Generiranje 415/1000
Generiranje 416/1000
Generiranje 417/1000
Generiranje 418/1000
Generiranje 419/1000
Generiranje 420/1000
Generiranje 421/1000
Generiranje 422/1000
Generiranje 423/1000
Generiranje 424/1000
Generiranje 425/1000
Generiranje 426/1000
Generiranje 427/1000
Generiranje 428/1000
Generiranje 429/1000
Generiranje 430/1000
Generiranje 431/1000
Generiranje 432/1000
Generiranje 433/1000
Generiranje 434/1000
Generiranje 435/1000
Generiranje 436/1000
Generiranje 437/1000
Generiranje 438/1000
Generiranje 439/1000
Generiranje 440/1000
Generiranje 441/1000
Pokusaj 1 nije uspio: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'The service is currently unavailable.', 'status': 'UNAVAILABLE'}}
Generiranje 442/1000
Generiranje 443/1000
Generiranje 444/1000
Generiranje 445/1000
Generiranje 446/1000
Generiranje 447/1000
Generiranje 448/1000
Generiranje 449/1000
Generiranje 450/1000
Generiranje 451/1000
Generiranje 452/1000
Generiranje 453/1000
Generiranje 454/1000
Generiranje 455/1000
Generiranje 456/1000
Generiranje 457/1000
Generiranje 458/1000
Generiranje 459/1000
Generiranje 460/1000
Generiranje 461/1000
Generiranje 462/1000
Generiranje 463/1000
Generiranje 464/1000
Generiranje 465/1000
Generiranje 466/1000
Generiranje 467/1000
Generiranje 468/1000
Generiranje 469/1000
Generiranje 470/1000
Generiranje 471/1000
Generiranje 472/1000
Generiranje 473/1000
Generiranje 474/1000
Generiranje 475/1000
Generiranje 476/1000
Generiranje 477/1000
Generiranje 478/1000
Generiranje 479/1000
Generiranje 480/1000
Generiranje 481/1000
Generiranje 482/1000
Generiranje 483/1000
Generiranje 484/1000
Generiranje 485/1000
Generiranje 486/1000
Generiranje 487/1000
Generiranje 488/1000
Generiranje 489/1000
Generiranje 490/1000
Generiranje 491/1000
Generiranje 492/1000
Generiranje 493/1000
Generiranje 494/1000
Generiranje 495/1000
Generiranje 496/1000
Generiranje 497/1000
Generiranje 498/1000
Generiranje 499/1000
Generiranje 500/1000
Generiranje 501/1000
Generiranje 502/1000
Generiranje 503/1000
Generiranje 504/1000
Generiranje 505/1000
Generiranje 506/1000
Generiranje 507/1000
Generiranje 508/1000
Generiranje 509/1000
Generiranje 510/1000
Generiranje 511/1000
Generiranje 512/1000
Generiranje 513/1000
Generiranje 514/1000
Generiranje 515/1000
Generiranje 516/1000
Generiranje 517/1000
Generiranje 518/1000
Generiranje 519/1000
Generiranje 520/1000
Generiranje 521/1000
Generiranje 522/1000
Generiranje 523/1000
Generiranje 524/1000
Generiranje 525/1000
Generiranje 526/1000
Generiranje 527/1000
Generiranje 528/1000
Generiranje 529/1000
Generiranje 530/1000
Generiranje 531/1000
Generiranje 532/1000
Generiranje 533/1000
Generiranje 534/1000
Generiranje 535/1000
Generiranje 536/1000
Generiranje 537/1000
Generiranje 538/1000
Generiranje 539/1000
Pokusaj 1 nije uspio: 1 validation error for SyntheticBatch
  JSON input should be string, bytes or bytearray [type=json_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydanti
Pokusaj 2 nije uspio: 1 validation error for SyntheticBatch
  JSON input should be string, bytes or bytearray [type=json_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydanti
Pokusaj 3 nije uspio: 1 validation error for SyntheticBatch
  JSON input should be string, bytes or bytearray [type=json_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydanti
Pokusaj 4 nije uspio: 1 validation error for SyntheticBatch
  JSON input should be string, bytes or bytearray [type=json_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydanti
Preskoceno, generiranje nije uspjelo.
Generiranje 540/1000
Generiranje 541/1000
Generiranje 542/1000
Generiranje 543/1000
Generiranje 544/1000
Generiranje 545/1000
Generiranje 546/1000
Generiranje 547/1000
Generiranje 548/1000
Generiranje 549/1000
Generiranje 550/1000
Generiranje 551/1000
Generiranje 552/1000
Generiranje 553/1000
Generiranje 554/1000
Generiranje 555/1000
Generiranje 556/1000
Generiranje 557/1000
Generiranje 558/1000
Generiranje 559/1000
Generiranje 560/1000
Generiranje 561/1000
Generiranje 562/1000
Generiranje 563/1000
Generiranje 564/1000
Generiranje 565/1000
Generiranje 566/1000
Generiranje 567/1000
Generiranje 568/1000
Generiranje 569/1000
Generiranje 570/1000
Generiranje 571/1000
Generiranje 572/1000
Generiranje 573/1000
Generiranje 574/1000
Generiranje 575/1000
Generiranje 576/1000
Generiranje 577/1000
Generiranje 578/1000
Generiranje 579/1000
Generiranje 580/1000
Generiranje 581/1000
Generiranje 582/1000
Generiranje 583/1000
Generiranje 584/1000
Generiranje 585/1000
Generiranje 586/1000
Generiranje 587/1000
Generiranje 588/1000
Generiranje 589/1000
Generiranje 590/1000
Generiranje 591/1000
Generiranje 592/1000
Generiranje 593/1000
Generiranje 594/1000
Generiranje 595/1000
Generiranje 596/1000
Generiranje 597/1000
Generiranje 598/1000
Generiranje 599/1000
Generiranje 600/1000
Generiranje 601/1000
Generiranje 602/1000
Generiranje 603/1000
Generiranje 604/1000
Generiranje 605/1000
Generiranje 606/1000
Generiranje 607/1000
Generiranje 608/1000
Generiranje 609/1000
Generiranje 610/1000
Generiranje 611/1000
Generiranje 612/1000
Generiranje 613/1000
Generiranje 614/1000
Generiranje 615/1000
Generiranje 616/1000
Generiranje 617/1000
Generiranje 618/1000
Generiranje 619/1000
Generiranje 620/1000
Generiranje 621/1000
Generiranje 622/1000
Generiranje 623/1000
Generiranje 624/1000
Generiranje 625/1000
Generiranje 626/1000
Generiranje 627/1000
Generiranje 628/1000
Generiranje 629/1000
Generiranje 630/1000
Generiranje 631/1000
Generiranje 632/1000
Generiranje 633/1000
Generiranje 634/1000
Generiranje 635/1000
Generiranje 636/1000
Generiranje 637/1000
Generiranje 638/1000
Generiranje 639/1000
Generiranje 640/1000
Generiranje 641/1000
Generiranje 642/1000
Generiranje 643/1000
Generiranje 644/1000
Generiranje 645/1000
Generiranje 646/1000
Generiranje 647/1000
Generiranje 648/1000
Generiranje 649/1000
Generiranje 650/1000
Generiranje 651/1000
Generiranje 652/1000
Generiranje 653/1000
Generiranje 654/1000
Generiranje 655/1000
Generiranje 656/1000
Generiranje 657/1000
Generiranje 658/1000
Generiranje 659/1000
Generiranje 660/1000
Generiranje 661/1000
Generiranje 662/1000
Generiranje 663/1000
Generiranje 664/1000
Generiranje 665/1000
Generiranje 666/1000
Generiranje 667/1000
Generiranje 668/1000
Generiranje 669/1000
Generiranje 670/1000
Generiranje 671/1000
Generiranje 672/1000
Generiranje 673/1000
Generiranje 674/1000
Generiranje 675/1000
Generiranje 676/1000
Generiranje 677/1000
Generiranje 678/1000
Generiranje 679/1000
Generiranje 680/1000
Generiranje 681/1000
Generiranje 682/1000
Generiranje 683/1000
Generiranje 684/1000
Generiranje 685/1000
Generiranje 686/1000
Generiranje 687/1000
Generiranje 688/1000
Generiranje 689/1000
Generiranje 690/1000
Generiranje 691/1000
Generiranje 692/1000
Generiranje 693/1000
Generiranje 694/1000
Generiranje 695/1000
Generiranje 696/1000
Generiranje 697/1000
Generiranje 698/1000
Generiranje 699/1000
Generiranje 700/1000
Generiranje 701/1000
Generiranje 702/1000
Generiranje 703/1000
Generiranje 704/1000
Generiranje 705/1000
Generiranje 706/1000
Generiranje 707/1000
Generiranje 708/1000
Generiranje 709/1000
Generiranje 710/1000
Generiranje 711/1000
Generiranje 712/1000
Generiranje 713/1000
Generiranje 714/1000
Generiranje 715/1000
Generiranje 716/1000
Generiranje 717/1000
Generiranje 718/1000
Generiranje 719/1000
Generiranje 720/1000
Generiranje 721/1000
Generiranje 722/1000
Generiranje 723/1000
Generiranje 724/1000
Generiranje 725/1000
Generiranje 726/1000
Generiranje 727/1000
Generiranje 728/1000
Generiranje 729/1000
Generiranje 730/1000
Generiranje 731/1000
Generiranje 732/1000
Generiranje 733/1000
Generiranje 734/1000
Generiranje 735/1000
Generiranje 736/1000
Generiranje 737/1000
Generiranje 738/1000
Generiranje 739/1000
Generiranje 740/1000
Generiranje 741/1000
Generiranje 742/1000
Generiranje 743/1000
Generiranje 744/1000
Generiranje 745/1000
Generiranje 746/1000
Generiranje 747/1000
Generiranje 748/1000
Generiranje 749/1000
Generiranje 750/1000
Generiranje 751/1000
Generiranje 752/1000
Generiranje 753/1000
Generiranje 754/1000
Generiranje 755/1000
Generiranje 756/1000
Generiranje 757/1000
Generiranje 758/1000
Generiranje 759/1000
Generiranje 760/1000
Generiranje 761/1000
Generiranje 762/1000
Generiranje 763/1000
Generiranje 764/1000
Generiranje 765/1000
Generiranje 766/1000
Generiranje 767/1000
Generiranje 768/1000
Generiranje 769/1000
Generiranje 770/1000
Generiranje 771/1000
Generiranje 772/1000
Generiranje 773/1000
Generiranje 774/1000
Generiranje 775/1000
Generiranje 776/1000
Generiranje 777/1000
Generiranje 778/1000
Generiranje 779/1000
Generiranje 780/1000
Generiranje 781/1000
Generiranje 782/1000
Generiranje 783/1000
Generiranje 784/1000
Generiranje 785/1000
Generiranje 786/1000
Generiranje 787/1000
Generiranje 788/1000
Generiranje 789/1000
Generiranje 790/1000
Generiranje 791/1000
Generiranje 792/1000
Generiranje 793/1000
Generiranje 794/1000
Generiranje 795/1000
Generiranje 796/1000
Generiranje 797/1000
Generiranje 798/1000
Generiranje 799/1000
Generiranje 800/1000
Generiranje 801/1000
Generiranje 802/1000
Generiranje 803/1000
Generiranje 804/1000
Generiranje 805/1000
Generiranje 806/1000
Generiranje 807/1000
Generiranje 808/1000
Generiranje 809/1000
Generiranje 810/1000
Generiranje 811/1000
Generiranje 812/1000
Generiranje 813/1000
Generiranje 814/1000
Generiranje 815/1000
Generiranje 816/1000
Generiranje 817/1000
Generiranje 818/1000
Generiranje 819/1000
Generiranje 820/1000
Generiranje 821/1000
Generiranje 822/1000
Generiranje 823/1000
Generiranje 824/1000
Generiranje 825/1000
Generiranje 826/1000
Generiranje 827/1000
Generiranje 828/1000
Generiranje 829/1000
Generiranje 830/1000
Generiranje 831/1000
Generiranje 832/1000
Generiranje 833/1000
Generiranje 834/1000
Generiranje 835/1000
Generiranje 836/1000
Generiranje 837/1000
Generiranje 838/1000
Generiranje 839/1000
Generiranje 840/1000
Generiranje 841/1000
Generiranje 842/1000
Generiranje 843/1000
Generiranje 844/1000
Generiranje 845/1000
Generiranje 846/1000
Generiranje 847/1000
Generiranje 848/1000
Generiranje 849/1000
Generiranje 850/1000
Generiranje 851/1000
Generiranje 852/1000
Generiranje 853/1000
Generiranje 854/1000
Generiranje 855/1000
Generiranje 856/1000
Generiranje 857/1000
Generiranje 858/1000
Generiranje 859/1000
Generiranje 860/1000
Generiranje 861/1000
Generiranje 862/1000
Generiranje 863/1000
Generiranje 864/1000
Generiranje 865/1000
Generiranje 866/1000
Generiranje 867/1000
Generiranje 868/1000
Generiranje 869/1000
Generiranje 870/1000
Generiranje 871/1000
Generiranje 872/1000
Generiranje 873/1000
Generiranje 874/1000
Generiranje 875/1000
Generiranje 876/1000
Generiranje 877/1000
Generiranje 878/1000
Generiranje 879/1000
Generiranje 880/1000
Generiranje 881/1000
Generiranje 882/1000
Generiranje 883/1000
Generiranje 884/1000
Generiranje 885/1000
Generiranje 886/1000
Generiranje 887/1000
Generiranje 888/1000
Generiranje 889/1000

In [19]:
#ucitavanje postojeceg synthetic_train.csv (ne pokretati ponovno ono gore)
synthetic_train = pd.read_csv(
    SYNTHETIC_PATH
)

print(
    "Ucitanih synthetic primjera:",
    len(synthetic_train)
)

synthetic_train.head()

Ucitanih synthetic primjera: 2997

,source_id,title,text,full_text,label,original_type,manipulation_type,change_summary,synthetic
0,isot_16792,Soccer star Weah to face vice president in Lib...,MONROVIA ( ) - Former soccer star George Weah ...,Soccer star Weah to face vice president in Lib...,1,synthetic,fact_change,Changed the vote margin lead from 10 points to...,True
1,isot_16792,You Won't Believe What This Soccer Legend Just...,MONROVIA ( ) - Former soccer star George Weah ...,You Won't Believe What This Soccer Legend Just...,1,synthetic,clickbait,"Rewrote the title into a dramatic, attention-g...",True
2,isot_16792,Shocking Showdown: Soccer Icon Weah Collides W...,MONROVIA ( ) - In a stunning political earthqu...,Shocking Showdown: Soccer Icon Weah Collides W...,1,synthetic,tone_shift,Shifted the tone of the entire article to be d...,True
3,isot_13888,Russia sends research ship to help search for ...,MOSCOW ( ) - Russia s defense ministry has sen...,Russia sends research ship to help search for ...,1,synthetic,fact_change,Changed the depth capability of the Yantar fro...,True
4,isot_13888,You Won't Believe Why Russia Just Sent This Ma...,MOSCOW ( ) - Russia s defense ministry has sen...,You Won't Believe Why Russia Just Sent This Ma...,1,synthetic,clickbait,Rewrote the title into a dramatic clickbait st...,True

In [20]:
# uklanjanje duplikata ako postoje
synthetic_train = (
    synthetic_train
    .drop_duplicates(subset=["full_text"])
    .reset_index(drop=True)
)

In [ ]:
# spremanje synthetic skupa (nema potrebe pokretati opet)
synthetic_train.to_csv(
    SYNTHETIC_PATH,
    index=False
)

In [21]:
#priprema originalnih train podataka
original_train = train_df.copy()

original_train["manipulation_type"] = "original"
original_train["change_summary"] = ""
original_train["synthetic"] = False
original_train["data_source"] = "original_train"
synthetic_train["data_source"] = "synthetic"

In [22]:
# isti stupci za originalne i sinteticke podatke
columns = [
    "source_id",
    "title",
    "text",
    "full_text",
    "label",
    "original_type",
    "manipulation_type",
    "change_summary",
    "synthetic",
    "data_source"
]

In [23]:
original_train = original_train[columns]
synthetic_train = synthetic_train[columns]

In [24]:
# spajanje originalnih i sintetickih podataka
augmented_train = pd.concat(
    [original_train, synthetic_train],
    ignore_index=True
)

print("Original train:", len(original_train))
print("Synthetic:", len(synthetic_train))
print("Augmented:", len(augmented_train))

Original train: 31268
Synthetic: 2997
Augmented: 34265

In [ ]:
# spremanje augmented train skupa (ne dirat ponovno)
augmented_train.to_csv(
    AUGMENTED_PATH,
    index=False
)

print("Augmented train podaci spremljeni")

Podaci spremljeni.

In [25]:
#ucitavanje testnog skupa
test_df = pd.read_csv(
    TEST_PATH
)

print(
    "Broj test primjera:",
    len(test_df)
)

Broj test primjera: 7818

In [26]:
#izdvajanje samo stvarnih vijesti iz test skupa (za generiranje challenge testa (tj fake vijesti uz pomoc llm-a))
#fake vijesti iz testnog dijela odbacujemo, te ce u challenge_test.csv bit samo prave vijesti te generirane fake vijesti 

real_test = (
    test_df[
        test_df["label"] == 0
    ]
    .copy()
    .reset_index(drop=True)
)

print(
    "Broj real test vijesti:",
    len(real_test)
)

Broj real test vijesti: 4239

In [27]:
#odabir stvarnih test vijesti za challenge test
SEED = 42

N_CHALLENGE_SOURCES = 200

challenge_sources = (
    real_test
    .sample(
        n=min(
            N_CHALLENGE_SOURCES,
            len(real_test)
        ),
        random_state=SEED
    )
    .reset_index(drop=True)
)

print(
    "Broj challenge izvora:",
    len(challenge_sources)
)

Broj challenge izvora: 200

In [28]:
#za GENERATION_MODEL koristio se gemini-3.5.-flash-lite tako augmented model nece nauciti specifican stil generatora kojeg je vidio tokom treninga
CHALLENGE_MODEL = "gemini-3.5-flash"

In [ ]:
#generiranje challenge testa (tj generiranje fake vijesti iz stvarnih vijesti iz testnog skupa) (ne pokretati ponovno)
challenge_synthetic = (
    generate_synthetic_dataset(
        source_df=challenge_sources,
        client=client,
        model_name=CHALLENGE_MODEL
    )
)

print(
    "Generirano challenge primjera:",
    len(challenge_synthetic)
)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Generiranje 1/200
Generiranje 2/200
Generiranje 3/200
Generiranje 4/200
Generiranje 5/200
Generiranje 6/200
Generiranje 7/200
Generiranje 8/200
Generiranje 9/200
Generiranje 10/200
Generiranje 11/200
Generiranje 12/200
Generiranje 13/200
Generiranje 14/200
Generiranje 15/200
Generiranje 16/200
Generiranje 17/200
Generiranje 18/200
Generiranje 19/200
Generiranje 20/200
Generiranje 21/200
Generiranje 22/200
Generiranje 23/200
Generiranje 24/200
Generiranje 25/200
Generiranje 26/200
Generiranje 27/200
Generiranje 28/200
Generiranje 29/200
Generiranje 30/200
Generiranje 31/200
Generiranje 32/200
Generiranje 33/200
Generiranje 34/200
Generiranje 35/200
Generiranje 36/200
Generiranje 37/200
Generiranje 38/200
Generiranje 39/200
Generiranje 40/200
Generiranje 41/200
Generiranje 42/200
Generiranje 43/200
Generiranje 44/200
Generiranje 45/200
Generiranje 46/200
Generiranje 47/200
Generiranje 48/200
Generiranje 49/200
Generiranje 50/200
Generiranje 51/200
Generiranje 52/200
Generiranje 53/200
Generiranje 54/200
Generiranje 55/200
Generiranje 56/200
Generiranje 57/200
Generiranje 58/200
Generiranje 59/200
Generiranje 60/200
Generiranje 61/200
Generiranje 62/200
Generiranje 63/200
Generiranje 64/200
Generiranje 65/200
Generiranje 66/200
Generiranje 67/200
Generiranje 68/200
Generiranje 69/200
Generiranje 70/200
Generiranje 71/200
Generiranje 72/200
Generiranje 73/200
Generiranje 74/200
Generiranje 75/200
Generiranje 76/200
Generiranje 77/200
Generiranje 78/200
Generiranje 79/200
Generiranje 80/200
Generiranje 81/200
Generiranje 82/200
Generiranje 83/200
Generiranje 84/200
Generiranje 85/200
Generiranje 86/200
Generiranje 87/200
Generiranje 88/200
Generiranje 89/200
Generiranje 90/200
Generiranje 91/200
Generiranje 92/200
Generiranje 93/200
Generiranje 94/200
Generiranje 95/200
Generiranje 96/200
Generiranje 97/200
Generiranje 98/200
Generiranje 99/200
Generiranje 100/200
Generiranje 101/200
Generiranje 102/200
Generiranje 103/200
Generiranje 104/200
Generiranje 105/200
Generiranje 106/200
Generiranje 107/200
Generiranje 108/200
Generiranje 109/200
Generiranje 110/200
Generiranje 111/200
Generiranje 112/200
Generiranje 113/200
Generiranje 114/200
Generiranje 115/200
Generiranje 116/200
Generiranje 117/200
Generiranje 118/200
Generiranje 119/200
Generiranje 120/200
Generiranje 121/200
Generiranje 122/200
Generiranje 123/200
Generiranje 124/200
Generiranje 125/200
Generiranje 126/200
Generiranje 127/200
Generiranje 128/200
Generiranje 129/200
Generiranje 130/200
Generiranje 131/200
Generiranje 132/200
Generiranje 133/200
Generiranje 134/200
Generiranje 135/200
Generiranje 136/200
Generiranje 137/200
Generiranje 138/200
Generiranje 139/200
Generiranje 140/200
Generiranje 141/200
Generiranje 142/200
Generiranje 143/200
Generiranje 144/200
Generiranje 145/200
Generiranje 146/200
Generiranje 147/200
Generiranje 148/200
Generiranje 149/200
Generiranje 150/200
Generiranje 151/200
Generiranje 152/200
Generiranje 153/200
Generiranje 154/200
Generiranje 155/200
Generiranje 156/200
Generiranje 157/200
Generiranje 158/200
Generiranje 159/200
Generiranje 160/200
Generiranje 161/200
Generiranje 162/200
Generiranje 163/200
Generiranje 164/200
Generiranje 165/200
Generiranje 166/200
Generiranje 167/200
Generiranje 168/200
Generiranje 169/200
Generiranje 170/200
Generiranje 171/200
Generiranje 172/200
Generiranje 173/200
Generiranje 174/200
Generiranje 175/200
Generiranje 176/200
Generiranje 177/200
Generiranje 178/200
Generiranje 179/200
Generiranje 180/200
Generiranje 181/200
Generiranje 182/200
Generiranje 183/200
Generiranje 184/200
Generiranje 185/200
Generiranje 186/200
Generiranje 187/200
Generiranje 188/200
Generiranje 189/200
Generiranje 190/200
Generiranje 191/200
Generiranje 192/200
Generiranje 193/200
Generiranje 194/200
Generiranje 195/200
Generiranje 196/200
Generiranje 197/200
Generiranje 198/200
Generiranje 199/200
Generiranje 200/200
Generirano challenge primjera: 600

In [ ]:
#ne pokretati ponovno niti ono sve ispod...samo zadnju celiju za ucitavanje kreiranog challenge_testa
print(
    challenge_synthetic[
        "manipulation_type"
    ]
    .value_counts()
)

manipulation_type
fact_change    200
clickbait      200
tone_shift     200
Name: count, dtype: int64

In [19]:
challenge_synthetic[
    "generator_model"
] = CHALLENGE_MODEL

In [20]:
challenge_synthetic[
    "synthetic"
] = True

In [ ]:
#oznacavanje originalnih test vijesti za challenge test
challenge_real = (
    challenge_sources.copy()
)

challenge_real[
    "manipulation_type"
] = "original"

challenge_real[
    "change_summary"
] = ""

challenge_real[
    "synthetic"
] = False

challenge_real[
    "generator_model"
] = "none"

In [22]:
challenge_columns = [
    "source_id",
    "title",
    "text",
    "full_text",
    "label",
    "original_type",
    "manipulation_type",
    "change_summary",
    "synthetic",
    "generator_model"
]

In [ ]:
challenge_real = challenge_real[challenge_columns]

challenge_synthetic = challenge_synthetic[challenge_columns]

In [ ]:
#spajanje originalnih i sintetickih podataka u challenge test
challenge_test = pd.concat(
    [
        challenge_real,
        challenge_synthetic
    ],
    ignore_index=True
)

In [25]:
print(
    "Original real:",
    len(challenge_real)
)

print(
    "Synthetic manipulated:",
    len(challenge_synthetic)
)

print(
    "Challenge ukupno:",
    len(challenge_test)
)

Original real: 200
Synthetic manipulated: 600
Challenge ukupno: 800

In [ ]:
#spremanje
challenge_test.to_csv(
    CHALLENGE_PATH,
    index=False
)

print(
    "Challenge test spremljen:"
)

print(
    CHALLENGE_PATH
)

Challenge test spremljen:
c:\Users\Korisnik\Desktop\ZNANSTVENO_PROGRAMIRANJE\projekt\2025-sci-prog\projects\synteticnewswithLLMs-ldanolic\data\processed\challenge_test.csv

In [29]:
#ucitavanje generiranog dataseta
challenge_test = pd.read_csv(
    CHALLENGE_PATH
)

print(
    "Broj spremljenih challenge primjera:",
    len(challenge_test)
)

print(
    challenge_test[
        "manipulation_type"
    ].value_counts()
)

challenge_test.head()

Broj spremljenih challenge primjera: 800
manipulation_type
original       200
fact_change    200
clickbait      200
tone_shift     200
Name: count, dtype: int64

,source_id,title,text,full_text,label,original_type,manipulation_type,change_summary,synthetic,generator_model
0,isot_15152,Cuban opposition falls at first hurdle as Cast...,HAVANA ( ) - Cuban opposition leaders said the...,Cuban opposition falls at first hurdle as Cast...,0,real,original,NaN,False,none
1,isot_06042,Ryan says Trump to address joint session of Co...,WASHINGTON ( ) - U.S. House of Representatives...,Ryan says Trump to address joint session of Co...,0,real,original,NaN,False,none
2,isot_04940,Senators want food safety review when U.S. fir...,WASHINGTON ( ) - Two U.S. senators from Midwes...,Senators want food safety review when U.S. fir...,0,real,original,NaN,False,none
3,isot_10625,House Republicans ready legal fight against Ob...,WASHINGTON ( ) - Republicans in the House of R...,House Republicans ready legal fight against Ob...,0,real,original,NaN,False,none
4,isot_04809,New York governor unveils South Bronx highway ...,( ) - New York Democratic Governor Andrew Cuom...,New York governor unveils South Bronx highway ...,0,real,original,NaN,False,none

In [7]:
train_df = pd.read_csv("data/processed/train.csv")
synthetic_train = pd.read_csv("data/processed/synthetic_train.csv")

augmented_train = pd.concat(
    [train_df, synthetic_train],
    ignore_index=True
)

augmented_train.to_csv(
    "data/processed/augmented_train.csv",
    index=False
)

print("Train:", len(train_df))
print("Synthetic:", len(synthetic_train))
print("Augmented:", len(augmented_train))

Train: 31268
Synthetic: 2997
Augmented: 34265